openapi: '3.0.3'

info:
  title: Bassify
  version: '1.0'

# servers:
#   - url: https://localhost:0000/api/v1


tags:
  - name: Tracks
    x-tag-expanded: true
  - name: Account
    x-tag-expanded: true

paths:

  ######################### TRACKS #########################
  /tracks/discover/random/{id_user}:
    post:
      description: | 
        Devuelve las X canciones nuevas para descubrir, 
        usando el algoritmo aleatorio.
      tags:
        - Tracks

      responses:
        '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    tracks:
                      type: array
                      description: "El array con todas las canciones"
                      items:
                        $ref: '#/components/schemas/Track'
      parameters:
        - name: id_user
          in: path
          required: true
          description: ID del usuario para el descubrimiento de canciones
          schema:
            type: string


      
        





  ######################### ACCOUNT #########################




components:
  schemas:

    Track:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

        previewUrl:
          type: string
          description: "Una URL a un archivo.mp3 de una preview sonora"
        imageUrl:
          type: string
          description: "Una URL a la imagen de portada"

        author:
          type: object
          description: "El author"
          $ref: '#/components/schemas/Artist'


    Artist:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          
        genres:
          type: array
          items:
            type: string
                                
